codecov:
  require_ci_to_pass: true
  branch: main

coverage:
  precision: 2
  round: down
  range: 75..95
  status:
    project:
      default:
        target: 70%
        threshold: 5%

        if_ci_failed: error
