name: Hello World 🌍

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step in GH Actions
        run: echo "Hello action on event ${{ github.event_name }}!"

      - name: Second step in GH Actions by ${{ github.actor }}
        run: echo "repo - ${{ github.repository }} and job name - ${{ github.job }}"

      - name: One more step in GH Actions on ${{ runner.os }}
        run: echo "sha - ${{ github.sha }} and ref - ${{ github.ref }}"
